sudo: required

language: c

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.11.2
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)
    - CC_TEST_REPORTER_ID=3a88a5b114bb886a72e0a0910713e4a2a849bca846bfbf3de956014b52562790


language: ruby

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - make test-ci

  - if [ "$TRAVIS_TAG" != "" ]; then
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD ;
      docker build -t udalov/youtube-fetcher:$TRAVIS_TAG . ;
      docker push udalov/youtube-fetcher:$TRAVIS_TAG ;
    fi

  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD ;
      docker build -t udalov/youtube-fetcher:latest . ;
      docker push udalov/youtube-fetcher:latest ;
    fi
